<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Process\Exceptions\ProcessTimedOutException;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;
use Illuminate\Support\Str;

class MakeCatalogSubmodule extends Command
{
    protected $signature = 'module:make-submodule {module : Top-level module name, e.g. General} {submodule : Submodule name, e.g. Agama}';

    protected $description = 'Scaffold a Laravel module for one submodule (config/module-catalog.php is the source of truth)';

    public function handle(): int
    {
        $module = $this->argument('module');
        $submodule = $this->argument('submodule');

        $map = config('module-catalog');
        $known = collect($map[$module] ?? []);

        if (! $known->contains($submodule)) {
            $this->error("'{$module}/{$submodule}' bukan pasangan module/submodule yang valid.");

            if (! $known->isEmpty()) {
                $suggestions = $known->filter(fn ($s) => Str::contains(Str::lower($s), Str::lower(substr($submodule, 0, 3))))->take(5);
                if ($suggestions->isNotEmpty()) {
                    $this->line('Mirip: '.$suggestions->implode(', '));
                }
            } elseif (! array_key_exists($module, $map)) {
                $this->line('Modul tidak dikenal: '.$module.'. Modul valid: '.implode(', ', array_keys($map)));
            }

            return self::FAILURE;
        }

        // nwidart normalizes the module directory name to StudlyCase internally regardless
        // of separators in the given name, and does so inconsistently between path creation
        // and module lookup when given a hyphenated name (crashes with "fireEvent() on null")
        // — so we pre-compute the final studly form ourselves and pass that directly, keeping
        // directory/namespace/module.json name/modules_statuses.json key all identical.
        $name = Str::studly($module).Str::studly($submodule);

        try {
            $this->call('module:make', [
                'name' => [$name],
                '--api' => true,
            ]);
        } catch (ProcessTimedOutException $e) {
            // module:make's own internal `composer dump-autoload` call hits the Symfony
            // Process default 60s timeout once there are dozens of module composer.json
            // files for the merge-plugin to scan. The module itself is already fully
            // generated by this point — just re-run autoload dump with headroom.
            $this->warn('composer dump-autoload internal ke module:make timeout, ngulang manual dengan timeout lebih panjang...');
            Process::path(base_path())->timeout(300)->run('composer dump-autoload');
        }

        $this->stripUnusedScaffold($name);

        $this->call('module:manifest-cache');

        $this->info("Modul {$name} siap. Namespace: Modules\\{$name}");

        return self::SUCCESS;
    }

    /**
     * `module:make --api` still generates resources/views, resources/assets, vite.config.js
     * and package.json regardless of config/modules.php's generator.*.generate=false toggles
     * (that config only governs individual `module:make-*` sub-generators, not this one). This
     * app is API-only, so drop the dead weight immediately.
     */
    private function stripUnusedScaffold(string $name): void
    {
        $path = base_path("Modules/{$name}");

        foreach (['resources', 'vite.config.js', 'package.json'] as $item) {
            $target = "{$path}/{$item}";
            is_dir($target) ? File::deleteDirectory($target) : @unlink($target);
        }
    }
}
